# - alias: "good morning"
#   trigger:
#     platform: sun
#     event: sunrise
#     offset: "-00:15:00"
#   action:
#     service: light.turn_on
#     entity_id: light.right_nightstand

# Bedroom lights at night
- id: night_bedroom_lighting
  alias: Bedroom night mode
  initial_state: 'off'
  condition:
     - condition: state
       entity_id: 'device_tracker.bogart'
       state: 'home'
  trigger:
    platform: time
    at: "20:38:00"
  action:
    service: switch.turn_on
    entity_id: group.bedroom_lights

## Humidifier
- id: turn_on_humidifier
  alias: Turn on humidifier
  initial_state: 'off'
  condition:
     - condition: time
       after: '20:00:00'
       before: '07:00:00'
     # - condition: template
     #   value_template: '{{ states("sensor.humidity") | int < 30 }}'
     - condition: state
       entity_id: switch.01200405ecfabc0f6151
       state: 'off'
  trigger:
   - platform: template
     value_template: '{{ states("sensor.bedroom_humidity") | int < 48 }}'
  action:
    service: switch.turn_on
    entity_id: switch.01200405ecfabc0f6151

- id: turn_off_humidifier
  alias: Turn off humidifier
  initial_state: 'off'
  condition:
    - condition: state
      entity_id: switch.01200405ecfabc0f6151
      state: 'on'
  trigger:
    platform: template
    value_template: '{{ states("sensor.bedroom_humidity") | int >= 50 }}'
  action:
    service: switch.turn_off
    entity_id: switch.01200405ecfabc0f6151
