[
automation:
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:15:00"
  action:
    service: light.turn_on
    entity_id: light.right_nightstand
    data:
      # 900 seconds = 15 minutes
      transition: 900
]
