- id: test
  alias: testing
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'below_horizon'
      to: 'above_horizon'
  condition:
    - condition: state
      entity_id: 'device_tracker.bogart'
      state: 'home'
    - condition: numeric_state
      entity_id: 'sensor.bedroom_humidity'
      below: 48
  action:
      service: homeassistant.turn_on
      entity_id: switch.01200405ecfabc0f6151


# - id: day_lights
#   alias: good morning
#   trigger:
#     platform: sun
#     event: sunrise
#     offset: "-00:15:00"
#   action:
#     service: light.turn_on
#     entity_id: light.right_nightstand
#
# ## Humidifier
# # - id: turn_on_humidifier
# - alias: "Turn on humidifier"
#   # initial_state: 'off'
#   # condition:
#   #    - condition: time
#   #      after: '20:00:00'
#   #      before: '24:00:00'
#   condition:
#     - condition: state
#       entity_id: sun.sun
#       state: 'below_horizon'
#      # - condition: template
#      #   value_template: '{{ states("sensor.humidity") | int < 30 }}'
#    # - condition: state
#    #   entity_id: switch.01200405ecfabc0f6151
#    #   state: 'off'
#   trigger:
#     - platform: template
#       value_template: '{{ states("sensor.bedroom_humidity") | int < 48 }}'
#   action:
#     service: homeassistant.turn_on
#     entity_id: switch.01200405ecfabc0f6151
#
- id: turn_off_humidifier
  alias: Turn off humidifier
  # initial_state: 'off'
  condition:
    - condition: state
      entity_id: switch.01200405ecfabc0f6151
      state: 'on'
  trigger:
    platform: template
    value_template: '{{ states("sensor.bedroom_humidity") | int >= 50 }}'
  action:
    service: switch.turn_off
    entity_id: switch.01200405ecfabc0f6151


# Example automations.yaml entry
- id: basic  # <-- Required for editor to work, for automations created with the editor the id will be automatically generated.
  alias: Hello world
  trigger:
  - platform: state
    entity_id: sun.sun
    from: above_horizon
    to: below_horizon
  condition:
  - condition: numeric_state
    entity_id: sensor.nursery_humidity
    above: 37
    below: 45
    value_template: '{{ float(state.state) + 2 }}'
  action:
  - service: switch.01200405ecfabc0f6a2d
