
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Users
person:
  - name: Maria Campo
    id: 3da9d244c1284d7fabb083efe76cd6b1
    device_trackers:
      - device_tracker.mcs_iphone

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# CloudMQTT
mqtt:
  broker: tailor.cloudmqtt.com
  port: 10037
  username: !secret cloudmqtt_user
  password: !secret cloudmqtt_password

# Subscribe to CloudMQTT
# Example configuration.yaml entry
sensor:
# rpi-th-sens-1
  - platform: mqtt
    name: "Temperature"
    state_topic: "rpi-th-sens-1"
    unit_of_measurement: '°F'
    value_template: "{{ value_json.temperature }}"
  - platform: mqtt
    name: "Humidity"
    state_topic: "rpi-th-sens-1"
    unit_of_measurement: '%'
    value_template: "{{ value_json.humidity }}"

# rpi-th-sens-2
  - platform: mqtt
    name: "Temperature"
    state_topic: "rpi-th-sens-2"
    unit_of_measurement: '°F'
    value_template: "{{ value_json.temperature }}"
  - platform: mqtt
    name: "Humidity"
    state_topic: "rpi-th-sens-2"
    unit_of_measurement: '%'
    value_template: "{{ value_json.humidity }}"





# Apple TV tvOS 13
apple_tv_mrp:
  - name: Living Room
    host: 192.168.0.6
    port: 49152

    credentials: !secret apple_tv_mrp_cred
    # Airplay Credentials
    # credentials : !secret
    
# Discovery
discovery:
   enable:

# Logitech Harmony Configuration
remote:
  - platform: harmony
    name: livingroom
    host: 192.168.0.11

# Xiaomi Vacuum
#vacuum:
#  - platform: xiaomi_miio
#    host: 192.168.0.13
#    token: YOUR_TOKEN

# Smart Life
tuya:
  username: !secret tuya_user
  password: !secret tuya_password
  country_code: "1"
  platform: smart_life

# Camera Configuration
stream:
camera:
  - platform: ffmpeg
    input: !secret wyze_url
    name: Nursery Cam
